export const DEMOS = {
    "ANIM.BAS": "demo/anim.bas",
    "ARROW.BAS": "demo/arrow.bas",
    "CANVAS_TEST.BAS": "demo/canvas_test.bas",
    "DATA.BAS": "demo/data.bas",
    "DICT.BAS": "demo/dict.bas",
    "GRAPHICS.BAS": "demo/graphics.bas",
    "GRAPHICS_API.BAS": "demo/graphics_api.bas",
    "LOCATE.BAS": "demo/locate.bas",
    "MIXED.BAS": "demo/mixed.bas",
    "PALETTE.BAS": "demo/palette.bas",
    "PERFORMANCE.BAS": "demo/performance.bas",
    "RAY.BAS": "demo/ray.bas",
    "REGRESSION.BAS": "demo/regression.bas",
    "RGB_TEST.BAS": "demo/rgb_test.bas",
    "SOUND_TEST.BAS": "demo/sound_test.bas",
    "SUPERTREK_BWX.BAS": "demo/supertrek_bwx.bas",
    "TURTLE.BAS": "demo/turtle.bas",
    "TURTLE_STACK.BAS": "demo/turtle_stack.bas"
};
