export const HELP_DATA = {
    "SYSTEM & FILES": [
        { c: "RUN", d: "Executes the program currently in memory. Clears variables. &lt;ESC&gt; to halt execution.", e: "RUN" },
        { c: "LIST", d: "Displays the source code of the current program.", e: "LIST" },
        { c: "EDIT", d: "Edit an existing line.", e: "EDIT 50" },
        { c: "NEW", d: "Clears the current program from memory and resets variables.", e: "NEW" },
        { c: "SAVE", d: "Saves current program to browser local storage.", e: "SAVE \"MYGAME\"" },
        { c: "LOAD", d: "Loads a program from local storage or demo library.", e: "LOAD \"DEMO/GRAPHICS.BAS\"" },
        { c: "DIR", d: "Lists all saved files and available demos.", e: "DIR" },
        { c: "DOWNLOAD", d: "Downloads the program as a .BAS text file to your computer.", e: "DOWNLOAD \"GAME\"" },
        { c: "WHERE", d: "Shows the line number where the last program stopped.", e: "WHERE" },
        { c: "JSECHO", d: "Toggles echoing of output to the browser console for debugging.", e: "JSECHO" },
        { c: "HELP", d: "Opens this reference manual.", e: "HELP" },
        { c: "REM", d: "Remark/Comment. Line is ignored by interpreter.", e: "10 REM SETUP VARIABLES" },
        { c: "VARS", d: "Lists all currently defined variables.", e: "VARS" }
    ],
    "SCREEN & GRAPHICS": [
        { c: "HOME or CLS", d: "Clears the text screen and moves cursor to top-left.", e: "10 HOME" },
        { c: "GR_CLEAR", d: "Clears screen to current GR_COLOR.", e: "10 GR_CLEAR" },
        { c: "GR_COLOR", d: "Sets color (0-63).", e: "20 GR_COLOR=3" },
        { c: "GR_MOVETO", d: "Moves graphics cursor to X,Y.", e: "30 GR_MOVETO 100,100" },
        { c: "GR_LINETO", d: "Draws line to X,Y.", e: "40 GR_LINETO 200,200" },
        { c: "GR_RECT", d: "Draws outline rectangle W,H at cursor.", e: "50 GR_RECT 50,50" },
        { c: "GR_FRECT", d: "Draws filled rectangle W,H at cursor.", e: "60 GR_FRECT 50,50" },
        { c: "GR_ELLIPSE", d: "Draws outline ellipse W,H at cursor.", e: "70 GR_ELLIPSE 50,30" },
        { c: "GR_FELLIPSE", d: "Draws filled ellipse W,H at cursor.", e: "80 GR_FELLIPSE 50,30" },
        { c: "GR_TRI", d: "Draws triangle (x2,y2,x3,y3) from cursor.", e: "90 GR_TRI 200,200,100,200" },
        { c: "GR_FTRI", d: "Draws filled triangle.", e: "95 GR_FTRI 200,200,100,200" },
        { c: "GR_PRINT", d: "Prints text at graphics cursor.", e: "10 GR_PRINT \"SCORE: \"; S" },
        { c: "GR_FONT", d: "Sets font size for GR_PRINT.", e: "20 GR_FONT 10" },
        { c: "TEXT", d: "Legacy command (Clears screen in Mixed Mode).", e: "100 TEXT" },
        { c: "HGR", d: "Legacy command (Clears screen in Mixed Mode).", e: "10 HGR" },
        { c: "HGR2", d: "Legacy command (Clears screen in Mixed Mode).", e: "10 HGR2" },
        { c: "HCOLOR", d: "Legacy: Sets drawing color (0-7).", e: "20 HCOLOR = 3" },
        { c: "HPLOT", d: "Legacy: Plots a point or draws lines.", e: "30 HPLOT 0,0 TO 100,100" },
        { c: "HTAB", d: "Moves cursor to horizontal column X (1-40).", e: "10 HTAB 20" },
        { c: "VTAB", d: "Moves cursor to vertical row Y (1-24).", e: "20 VTAB 12" },
        { c: "SETPOS", d: "Moves cursor to X, Y coordinates (Custom).", e: "30 SETPOS 15, 10" }
    ],
    "I/O & CONTROL": [
        { c: "PRINT", d: "Outputs text or variables. Use ; to suppress newline.", e: "10 PRINT \"SCORE: \"; S" },
        { c: "INPUT", d: "Pauses to get value from user.", e: "20 INPUT \"NAME? \"; N$" },
        { c: "INKEY(M)", d: "Reads char. M=1 wait, M=0 async.", e: "A$ = INKEY(1)" },
        { c: "GOTO", d: "Unconditional jump to line number.", e: "50 GOTO 10" },
        { c: "GOSUB", d: "Jump to subroutine. Returns on RETURN.", e: "10 GOSUB 1000" },
        { c: "RETURN", d: "Return from subroutine.", e: "1000 RETURN" },
        { c: "IF...THEN", d: "Conditional execution.", e: "10 IF A > 10 THEN GOTO 50" },
        { c: "FOR...NEXT", d: "Loop structure.", e: "10 FOR I=1 TO 10 STEP 2 ... 50 NEXT I" },
        { c: "END", d: "Stops program execution.", e: "99 END" },
        { c: "DIM", d: "Defines array size.", e: "10 DIM A(100)" },
        { c: "LET", d: "Assigns value to variable (optional keyword).", e: "10 LET A = 5" }
    ],
    "MATH FUNCTIONS": [
        { c: "SIN(X)", d: "Sine of X (radians).", e: "Y = SIN(3.14)" },
        { c: "COS(X)", d: "Cosine of X (radians).", e: "Y = COS(0)" },
        { c: "TAN(X)", d: "Tangent of X.", e: "Y = TAN(1)" },
        { c: "ATN(X)", d: "Arctangent of X.", e: "Y = ATN(1)" },
        { c: "SQR(X)", d: "Square root.", e: "Y = SQR(16)" },
        { c: "ABS(X)", d: "Absolute value.", e: "Y = ABS(-5)" },
        { c: "INT(X)", d: "Integer part (Floor).", e: "Y = INT(3.9)" },
        { c: "EXP(X)", d: "e raised to power X.", e: "Y = EXP(1)" },
        { c: "LOG(X)", d: "Natural logarithm.", e: "Y = LOG(10)" },
        { c: "EXP(X)", d: "e raised to power X.", e: "Y = EXP(1)" },
        { c: "LOG(X)", d: "Natural logarithm.", e: "Y = LOG(10)" },
        { c: "RND(N)", d: "Random number 0 to N. Use N=1 for 0.0-1.0.", e: "R = RND(10)" },
        { c: "RAND(X)", d: "Random number 0 to X.", e: "R = RAND(100)" },
        { c: "SEED(N)", d: "Seed the random number generator.", e: "SEED(12345)" }
    ],
    "STRING FUNCTIONS": [
        { c: "LEN(S$)", d: "Length of string.", e: "L = LEN(\"ABC\")" },
        { c: "LEFT$(S$,N)", d: "First N chars.", e: "A$ = LEFT$(\"HELLO\", 2)" },
        { c: "RIGHT$(S$,N)", d: "Last N chars.", e: "A$ = RIGHT$(\"WORLD\", 3)" },
        { c: "MID$(S$,I,N)", d: "N chars starting at I.", e: "A$ = MID$(\"ABC\", 2, 1)" },
        { c: "STR$(N)", d: "Convert number to string.", e: "A$ = STR$(123)" },
        { c: "VAL(S$)", d: "Convert string to number.", e: "N = VAL(\"12.5\")" },
        { c: "INSTR(N,S$,Sub$)", d: "Search for string.", e: "P = INSTR(\"ABC\",\"B\")" }
    ]
};
