export const KEYWORDS = [
    // SYSTEM & FILES
    { name: "RUN", type: "COMMAND", category: "SYSTEM & FILES", desc: "Executes the program currently in memory. Clears variables. <ESC> to halt execution.", example: "RUN" },
    { name: "LIST", type: "COMMAND", category: "SYSTEM & FILES", desc: "Displays the source code of the current program.", example: "LIST" },
    { name: "EDIT", type: "COMMAND", category: "SYSTEM & FILES", desc: "Opens the full-screen code editor. Or use 'EDIT <line>' for single line.", example: "EDIT" },
    { name: "NEW", type: "COMMAND", category: "SYSTEM & FILES", desc: "Clears the current program from memory and resets variables.", example: "NEW" },
    { name: "COPY", type: "COMMAND", category: "SYSTEM & FILES", desc: "Copies the current program source code to your clipboard.", example: "COPY" },
    { name: "SAVE", type: "COMMAND", category: "SYSTEM & FILES", desc: "Saves current program to browser local storage.", example: "SAVE \"MYGAME\"" },
    { name: "LOAD", type: "COMMAND", category: "SYSTEM & FILES", desc: "Loads a program from local storage or demo library.", example: "LOAD \"DEMO/GRAPHICS.BAS\"" },
    { name: "DIR", type: "COMMAND", category: "SYSTEM & FILES", desc: "Lists all saved files and available demos.", example: "DIR" },
    { name: "CATALOG", type: "COMMAND", category: null, desc: "Alias for DIR", example: "CATALOG" }, // Alias
    { name: "DOWNLOAD", type: "COMMAND", category: "SYSTEM & FILES", desc: "Downloads the program as a .BAS text file to your computer.", example: "DOWNLOAD \"GAME\"" },
    { name: "UPLOAD", type: "COMMAND", category: "SYSTEM & FILES", desc: "Uploads a .BAS text file from your computer into memory.", example: "UPLOAD" },
    { name: "WHERE", type: "COMMAND", category: "SYSTEM & FILES", desc: "Shows the line number where the last program stopped.", example: "WHERE" },
    { name: "JSECHO", type: "COMMAND", category: "SYSTEM & FILES", desc: "Toggles echoing of output to the browser console for debugging.", example: "JSECHO" },
    { name: "JSPEEK", type: "COMMAND", category: "SYSTEM & FILES", desc: "See what your BASIC code looks like compiled to JavaScript.", example: "JSPEEK" },
    { name: "VIZ", type: "COMMAND", category: "SYSTEM & FILES", desc: "Generates an interactive flowchart visualization of your program's structure.", example: "VIZ" },
    { name: "HELP", type: "COMMAND", category: "SYSTEM & FILES", desc: "Opens this reference manual.", example: "HELP" },
    { name: "REM", type: "KEYWORD", category: "SYSTEM & FILES", desc: "Remark/Comment. Line is ignored by interpreter.", example: "10 REM SETUP VARIABLES" },
    { name: "VARS", type: "COMMAND", category: "SYSTEM & FILES", desc: "Lists all currently defined variables, or a specific variable if provided. Quotes are optional.", example: "VARS [\"varname\"]" },

    // SCREEN & GRAPHICS
    { name: "HOME", type: "COMMAND", category: "SCREEN & GRAPHICS", desc: "Clears the text screen and moves cursor to top-left.", example: "10 HOME" },
    { name: "CLS", type: "COMMAND", category: "SCREEN & GRAPHICS", desc: "Clears the text screen and moves cursor to top-left.", example: "10 CLS", helpSyntax: "HOME or CLS" },
    { name: "GR_CLEAR", type: "COMMAND", category: "SCREEN & GRAPHICS", desc: "Clears screen to current GR_COLOR.", example: "10 GR_CLEAR" },
    { name: "GR_CLS", type: "COMMAND", category: null, desc: "Alias for GR_CLEAR.", example: "10 GR_CLS" },
    { name: "GR_COLOR", type: "COMMAND", category: "SCREEN & GRAPHICS", desc: "Sets color (0-63).", example: "20 GR_COLOR=3" },
    { name: "GR_MOVETO", type: "COMMAND", category: "SCREEN & GRAPHICS", desc: "Moves graphics cursor to X,Y.", example: "30 GR_MOVETO 100,100" },
    { name: "GR_LINETO", type: "COMMAND", category: "SCREEN & GRAPHICS", desc: "Draws line to X,Y.", example: "40 GR_LINETO 200,200" },
    { name: "GR_RECT", type: "COMMAND", category: "SCREEN & GRAPHICS", desc: "Draws outline rectangle W,H at cursor.", example: "50 GR_RECT 50,50" },
    { name: "GR_FRECT", type: "COMMAND", category: "SCREEN & GRAPHICS", desc: "Draws filled rectangle W,H at cursor.", example: "60 GR_FRECT 50,50" },
    { name: "GR_ELLIPSE", type: "COMMAND", category: "SCREEN & GRAPHICS", desc: "Draws outline ellipse W,H at cursor.", example: "70 GR_ELLIPSE 50,30" },
    { name: "GR_FELLIPSE", type: "COMMAND", category: "SCREEN & GRAPHICS", desc: "Draws filled ellipse W,H at cursor.", example: "80 GR_FELLIPSE 50,30" },
    { name: "GR_TRI", type: "COMMAND", category: "SCREEN & GRAPHICS", desc: "Draws triangle (x2,y2,x3,y3) from cursor.", example: "90 GR_TRI 200,200,100,200" },
    { name: "GR_FTRI", type: "COMMAND", category: "SCREEN & GRAPHICS", desc: "Draws filled triangle.", example: "95 GR_FTRI 200,200,100,200" },
    { name: "GR_PRINT", type: "COMMAND", category: "SCREEN & GRAPHICS", desc: "Prints text at graphics cursor.", example: "10 GR_PRINT \"SCORE: \"; S" },
    { name: "GR_FONT", type: "COMMAND", category: "SCREEN & GRAPHICS", desc: "Sets font size for GR_PRINT.", example: "20 GR_FONT 10" },
    { name: "GR_RGB", type: "FUNCTION", category: "SCREEN & GRAPHICS", desc: "Returns nearest palette color index for RGB values 0-255.", example: "10 GR_COLOR GR_RGB(255,128,0)", helpSyntax: "GR_RGB(r,g,b)" },
    { name: "TEXT", type: "COMMAND", category: "SCREEN & GRAPHICS", desc: "Legacy command (Clears screen in Mixed Mode).", example: "100 TEXT" },
    { name: "HGR", type: "COMMAND", category: "SCREEN & GRAPHICS", desc: "Legacy command (Clears screen in Mixed Mode).", example: "10 HGR" },
    { name: "HGR2", type: "COMMAND", category: "SCREEN & GRAPHICS", desc: "Legacy command (Clears screen in Mixed Mode).", example: "10 HGR2" },
    { name: "HCOLOR", type: "COMMAND", category: "SCREEN & GRAPHICS", desc: "Legacy: Sets drawing color (0-7).", example: "20 HCOLOR = 3" },
    { name: "HPLOT", type: "COMMAND", category: "SCREEN & GRAPHICS", desc: "Legacy: Plots a point or draws lines.", example: "30 HPLOT 0,0 TO 100,100" },
    { name: "HTAB", type: "COMMAND", category: "SCREEN & GRAPHICS", desc: "Moves cursor to horizontal column X (1-40).", example: "10 HTAB 20" },
    { name: "VTAB", type: "COMMAND", category: "SCREEN & GRAPHICS", desc: "Moves cursor to vertical row Y (1-24).", example: "20 VTAB 12" },
    { name: "SETPOS", type: "COMMAND", category: "SCREEN & GRAPHICS", desc: "Moves cursor to X, Y coordinates (Custom).", example: "30 SETPOS 15, 10" },

    // TURTLE GRAPHICS
    { name: "GR_FWD", type: "COMMAND", category: "TURTLE GRAPHICS", desc: "Alias GR_FD. Moves turtle forward by distance.", example: "10 GR_FWD 50" },
    { name: "GR_FD", type: "COMMAND", category: null, desc: "Alias GR_FWD.", example: "10 GR_FD 50" },
    { name: "GR_BK", type: "COMMAND", category: "TURTLE GRAPHICS", desc: "Moves turtle backward by distance.", example: "20 GR_BK 50" },
    { name: "GR_RT", type: "COMMAND", category: "TURTLE GRAPHICS", desc: "Turns turtle right by degrees.", example: "30 GR_RT 90" },
    { name: "GR_LT", type: "COMMAND", category: "TURTLE GRAPHICS", desc: "Turns turtle left by degrees.", example: "40 GR_LT 90" },
    { name: "GR_PEN_DN", type: "COMMAND", category: "TURTLE GRAPHICS", desc: "Alias GR_PD. Puts the pen down to draw.", example: "50 GR_PEN_DN" },
    { name: "GR_PD", type: "COMMAND", category: null, desc: "Alias GR_PEN_DN", example: "50 GR_PD" },
    { name: "GR_PEN_UP", type: "COMMAND", category: "TURTLE GRAPHICS", desc: "Alias GR_PU. Lifts the pen to stop drawing.", example: "60 GR_PEN_UP" },
    { name: "GR_PU", type: "COMMAND", category: null, desc: "Alias GR_PEN_UP", example: "60 GR_PU" },
    { name: "GR_TURTLE_RESET", type: "COMMAND", category: "TURTLE GRAPHICS", desc: "Alias GR_TR. Resets turtle to 0,0 heading Up.", example: "70 GR_TURTLE_RESET" },
    { name: "GR_TR", type: "COMMAND", category: null, desc: "Alias GR_TURTLE_RESET", example: "70 GR_TR" },
    { name: "GR_PUSH", type: "COMMAND", category: "TURTLE GRAPHICS", desc: "Saves current graphics state (pos, heading, color, etc) to stack.", example: "80 GR_PUSH" },
    { name: "GR_POP", type: "COMMAND", category: "TURTLE GRAPHICS", desc: "Restores graphics state from stack.", example: "90 GR_POP" },

    // CANVAS BUFFERS
    { name: "GR_CANVAS", type: "FUNCTION", category: "CANVAS BUFFERS", desc: "Function: Creates an off-screen canvas dimensioned WxH and returns ID.", example: "ID = GR_CANVAS(100, 100)", helpSyntax: "GR_CANVAS(W, H)" },
    { name: "GR_GET_CANVAS", type: "FUNCTION", category: "CANVAS BUFFERS", desc: "Function: Returns the ID of the currently active canvas.", example: "C = GR_GET_CANVAS()", helpSyntax: "GR_GET_CANVAS()" },
    { name: "GR_CANVAS_WIDTH", type: "FUNCTION", category: "CANVAS BUFFERS", desc: "Function: Returns width of the active canvas.", example: "W = GR_CANVAS_WIDTH()" },
    { name: "GR_CANVAS_HEIGHT", type: "FUNCTION", category: "CANVAS BUFFERS", desc: "Function: Returns height of the active canvas.", example: "H = GR_CANVAS_HEIGHT()" },
    { name: "GR_SET_CANVAS", type: "COMMAND", category: "CANVAS BUFFERS", desc: "Command: Sets the active drawing target to canvas ID. ID 0 is main screen.", example: "10 GR_SET_CANVAS 1", helpSyntax: "GR_SET_CANVAS(ID)" },
    { name: "GR_COPY", type: "COMMAND", category: "CANVAS BUFFERS", desc: "Command: Copies canvas ID to X, Y on active canvas with optional W, H scaling.", example: "20 GR_COPY 1, 50, 50, 100, 100" },
    { name: "GR_FREE", type: "COMMAND", category: "CANVAS BUFFERS", desc: "Command: Frees memory for canvas ID.", example: "30 GR_FREE 1" },

    // I/O & CONTROL
    { name: "PRINT", type: "COMMAND", category: "I/O & CONTROL", desc: "Outputs text or variables. Use ; to suppress newline.", example: "10 PRINT \"SCORE: \"; S" },
    { name: "?", type: "COMMAND", category: null, desc: "Alias for PRINT", example: "? \"HELLO\"" },
    { name: "INPUT", type: "COMMAND", category: "I/O & CONTROL", desc: "Pauses to get value from user.", example: "20 INPUT \"NAME? \"; N$" },
    { name: "INKEY", type: "FUNCTION", category: "I/O & CONTROL", desc: "Reads char. M=1 wait, M=0 async.", example: "A$ = INKEY(1)", helpSyntax: "INKEY(M)" },
    { name: "INKEY$", type: "FUNCTION", category: null, desc: "Reads char.", example: "A$ = INKEY$(1)" },
    { name: "GOTO", type: "KEYWORD", category: "I/O & CONTROL", desc: "Unconditional jump to line number.", example: "50 GOTO 10" },
    { name: "GOSUB", type: "KEYWORD", category: "I/O & CONTROL", desc: "Jump to subroutine. Returns on RETURN.", example: "10 GOSUB 1000" },
    { name: "ON", type: "KEYWORD", category: "I/O & CONTROL", desc: "Jump to Nth line in list. ON N GOTO L1,L2", example: "10 ON N GOTO 100,200", helpSyntax: "ON...GOTO" },
    { name: "RETURN", type: "KEYWORD", category: "I/O & CONTROL", desc: "Return from subroutine or function.", example: "1000 RETURN" },
    { name: "FUN", type: "KEYWORD", category: "I/O & CONTROL", desc: "Define a sub-program function with local scoped arguments.", example: "FUN MATH(X) ... RETURN X", helpSyntax: "FUN..RETURN" },
    { name: "CALL", type: "KEYWORD", category: "I/O & CONTROL", desc: "Execute a function natively returning isolated values.", example: "Z = CALL MATH(1)" },
    { name: "!", type: "KEYWORD", category: null, desc: "Alias for CALL", example: "! MATH(1)" },
    { name: "DEF", type: "KEYWORD", category: null, desc: "Define function", example: "DEF FNA(X) = X*2" },
    { name: "IF", type: "KEYWORD", category: "I/O & CONTROL", desc: "Conditional execution.", example: "10 IF A > 10 THEN GOTO 50", helpSyntax: "IF...THEN" },
    { name: "THEN", type: "KEYWORD", category: null, desc: "Follows IF", example: "10 IF A > 10 THEN 50" },
    { name: "ELSE", type: "KEYWORD", category: null, desc: "Follows THEN", example: "10 IF A > 10 THEN 50 ELSE 60" },
    { name: "AND", type: "KEYWORD", category: "I/O & CONTROL", desc: "Logical operators for multiple conditions.", example: "10 IF A > 10 AND A < 20 THEN GOTO 50", helpSyntax: "AND / OR" },
    { name: "OR", type: "KEYWORD", category: null, desc: "Logical operator", example: "10 IF A > 10 OR B < 5 THEN 50" },
    { name: "FOR", type: "KEYWORD", category: "I/O & CONTROL", desc: "Loop structure.", example: "10 FOR I=1 TO 10 STEP 2 ... 50 NEXT I", helpSyntax: "FOR...NEXT" },
    { name: "NEXT", type: "KEYWORD", category: null, desc: "Ends a FOR loop", example: "50 NEXT I" },
    { name: "TO", type: "KEYWORD", category: null, desc: "Follows FOR", example: "10 FOR I=1 TO 10" },
    { name: "STEP", type: "KEYWORD", category: null, desc: "Follows TO", example: "10 FOR I=1 TO 10 STEP 2" },
    { name: "DELAY", type: "COMMAND", category: "I/O & CONTROL", desc: "Pauses execution for M milliseconds.", example: "10 DELAY 500" },
    { name: "END", type: "KEYWORD", category: "I/O & CONTROL", desc: "Stops program execution.", example: "99 END" },
    { name: "STOP", type: "KEYWORD", category: "I/O & CONTROL", desc: "Stops program execution (Same as END).", example: "99 STOP" },
    { name: "DIM", type: "COMMAND", category: "I/O & CONTROL", desc: "Allocates an uninitialized N-dimensional array. Also a function: LET A=DIM(10)", example: "10 DIM A(10, 10)" },
    { name: "ARRAY", type: "COMMAND", category: "I/O & CONTROL", desc: "Instantiates an array with given values. Also a function.", example: "20 ARRAY A(1, 2, 3)" },
    { name: "DICT", type: "COMMAND", category: "I/O & CONTROL", desc: "Defines an associative array/hash table. Also a function.", example: "10 DICT T(\"A\", 1, \"B\", 2)" },
    { name: "DATA", type: "COMMAND", category: "I/O & CONTROL", desc: "Stores static values to be read by READ.", example: "30 DATA \"key\", 1, 100" },
    { name: "READ", type: "COMMAND", category: "I/O & CONTROL", desc: "Reads N items from DATA into an array or dict.", example: "20 READ A, 10" },
    { name: "RESTORE", type: "COMMAND", category: "I/O & CONTROL", desc: "Resets the DATA pointer to read from a specific line.", example: "10 RESTORE 30" },
    { name: "NIL", type: "KEYWORD", category: "I/O & CONTROL", desc: "Constant for a missing or empty DICT value. Used to delete keys.", example: "40 T(\"A\") = NIL" },
    { name: "LET", type: "COMMAND", category: "I/O & CONTROL", desc: "Assigns value to variable (optional keyword).", example: "10 LET A = 5" },
    { name: "FORKEYS", type: "KEYWORD", category: "I/O & CONTROL", desc: "Loop through keys of a DICT.", example: "10 FORKEYS K, T ... 20 NEXT K" },

    // MATH FUNCTIONS
    { name: "SIN", type: "FUNCTION", category: "MATH FUNCTIONS", desc: "Sine of X (radians).", example: "Y = SIN(3.14)", helpSyntax: "SIN(X)" },
    { name: "COS", type: "FUNCTION", category: "MATH FUNCTIONS", desc: "Cosine of X (radians).", example: "Y = COS(0)", helpSyntax: "COS(X)" },
    { name: "TAN", type: "FUNCTION", category: "MATH FUNCTIONS", desc: "Tangent of X.", example: "Y = TAN(1)", helpSyntax: "TAN(X)" },
    { name: "ATN", type: "FUNCTION", category: "MATH FUNCTIONS", desc: "Arctangent of X.", example: "Y = ATN(1)", helpSyntax: "ATN(X)" },
    { name: "SQR", type: "FUNCTION", category: "MATH FUNCTIONS", desc: "Square root.", example: "Y = SQR(16)", helpSyntax: "SQR(X)" },
    { name: "ABS", type: "FUNCTION", category: "MATH FUNCTIONS", desc: "Absolute value.", example: "Y = ABS(-5)", helpSyntax: "ABS(X)" },
    { name: "SGN", type: "FUNCTION", category: "MATH FUNCTIONS", desc: "Sign value. Returns 1 for positive, -1 for negative, 0 for 0.", example: "Y = SGN(-10)", helpSyntax: "SGN(X)" },
    { name: "INT", type: "FUNCTION", category: "MATH FUNCTIONS", desc: "Integer part (Floor).", example: "Y = INT(3.9)", helpSyntax: "INT(X)" },
    { name: "EXP", type: "FUNCTION", category: "MATH FUNCTIONS", desc: "e raised to power X.", example: "Y = EXP(1)", helpSyntax: "EXP(X)" },
    { name: "LOG", type: "FUNCTION", category: "MATH FUNCTIONS", desc: "Natural logarithm.", example: "Y = LOG(10)", helpSyntax: "LOG(X)" },
    { name: "RND", type: "FUNCTION", category: "MATH FUNCTIONS", desc: "Random number 0 to N. Use N=1 for 0.0-1.0.", example: "R = RND(10)", helpSyntax: "RND(N)" },
    { name: "RAND", type: "FUNCTION", category: "MATH FUNCTIONS", desc: "Random number 0 to X.", example: "R = RAND(100)", helpSyntax: "RAND(X)" },
    { name: "SEED", type: "COMMAND", category: "MATH FUNCTIONS", desc: "Seed the random number generator.", example: "SEED(12345)", helpSyntax: "SEED(N)" },
    { name: "TIME", type: "FUNCTION", category: "MATH FUNCTIONS", desc: "Returns the current browser high-resolution time.", example: "T = TIME" },

    // STRING FUNCTIONS
    { name: "LEN", type: "FUNCTION", category: "STRING FUNCTIONS", desc: "Length of string.", example: "L = LEN(\"ABC\")", helpSyntax: "LEN(S$)" },
    { name: "LEFT$", type: "FUNCTION", category: "STRING FUNCTIONS", desc: "First N chars.", example: "A$ = LEFT$(\"HELLO\", 2)", helpSyntax: "LEFT$(S$,N)" },
    { name: "RIGHT$", type: "FUNCTION", category: "STRING FUNCTIONS", desc: "Last N chars.", example: "A$ = RIGHT$(\"WORLD\", 3)", helpSyntax: "RIGHT$(S$,N)" },
    { name: "MID$", type: "FUNCTION", category: "STRING FUNCTIONS", desc: "N chars starting at I.", example: "A$ = MID$(\"ABC\", 2, 1)", helpSyntax: "MID$(S$,I,N)" },
    { name: "UPPER$", type: "FUNCTION", category: "STRING FUNCTIONS", desc: "Convert to uppercase.", example: "U$ = UPPER$(\"abc\")", helpSyntax: "UPPER$(S$)" },
    { name: "LOWER$", type: "FUNCTION", category: "STRING FUNCTIONS", desc: "Convert to lowercase.", example: "L$ = LOWER$(\"XYZ\")", helpSyntax: "LOWER$(S$)" },
    { name: "STR$", type: "FUNCTION", category: "STRING FUNCTIONS", desc: "Convert number to string.", example: "A$ = STR$(123)", helpSyntax: "STR$(N)" },
    { name: "VAL", type: "FUNCTION", category: "STRING FUNCTIONS", desc: "Convert string to number.", example: "N = VAL(\"12.5\")", helpSyntax: "VAL(S$)" },
    { name: "ASC", type: "FUNCTION", category: "STRING FUNCTIONS", desc: "ASCII code of first character.", example: "C = ASC(\"A\")", helpSyntax: "ASC(S$)" },
    { name: "CHR$", type: "FUNCTION", category: "STRING FUNCTIONS", desc: "Single-char string from ASCII code.", example: "A$ = CHR$(65)", helpSyntax: "CHR$(N)" },
    { name: "INSTR", type: "FUNCTION", category: "STRING FUNCTIONS", desc: "Search for string.", example: "P = INSTR(\"ABC\",\"B\")", helpSyntax: "INSTR(N,S$,Sub$)" },

    // SOUND EFFECTS
    { name: "SFX_LOAD", type: "FUNCTION", category: "SOUND EFFECTS", desc: "Loads a sound effect and returns its ID.", example: "S = SFX_LOAD(\"laser.mp3\")", helpSyntax: "SFX_LOAD(URL$)" },
    { name: "SFX_PLAY", type: "COMMAND", category: "SOUND EFFECTS", desc: "Plays a sound effect asynchronously.", example: "SFX_PLAY(S)" },
    { name: "SFX_PLAY_WAIT", type: "COMMAND", category: "SOUND EFFECTS", desc: "Plays a sound effect synchronously.", example: "SFX_PLAY_WAIT(S)" }
];

export const SYNTAX_COMMANDS = KEYWORDS.filter(k => k.type === "COMMAND").map(k => k.name);
export const SYNTAX_KEYWORDS = KEYWORDS.filter(k => k.type === "KEYWORD").map(k => k.name);
export const SYNTAX_FUNCTIONS = KEYWORDS.filter(k => k.type === "FUNCTION").map(k => k.name);
