10 CLS
20 PRINT "LOADING SOUND..."
30 LET SND = SFX_LOAD("https://actions.google.com/sounds/v1/alarms/digital_watch_alarm_long.ogg")
40 PRINT "SOUND LOADED (ID: "; SND; ")."
50 PRINT "PRESS ANY KEY TO PLAY ASYNC."
60 LET A$ = INKEY$(1)
70 PRINT "PLAYING ASYNC (EXECUTION CONTINUES)..."
80 SFX_PLAY(SND)
90 PRINT "PRESS ANY KEY TO PLAY SYNC (WAIT)."
100 LET A$ = INKEY$(1)
110 PRINT "PLAYING WAIT (EXECUTION BLOCKED)..."
120 SFX_PLAY_WAIT(SND)
130 PRINT "DONE."
